project/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import ProjectView, dashboard_content, HomeView, project_create_view

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('dashboard/', dashboard_content, name='dashboard'),
    path('projects/', ProjectView.as_view(), name='project'),
    path('create/', project_create_view, name='project_create')
]

project_pros/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
    path('', include('top_tips.urls')),
    path("accounts/", include("allauth.urls")),
    path('', include('top_tips.urls')),
]

top_tips/urls.py
from django.urls import path
from .views import TopTipsView

urlpatterns = [
    path('top-tips/', TopTipsView.as_view(), name='top_tips'),
]

project/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class project_detail(models.Model):
    account = models.ForeignKey(User, on_delete=models.CASCADE, name="account")
    title = models.CharField(max_length=120)
    # featured_image = CloudinaryField('image', default='placeholder')
    summary = models.CharField(max_length=500)
    collaborators = models.CharField(max_length=120)
    deployed_site = models.CharField(max_length=2048)
    github_repo = models.CharField(max_length=2048)
    reflections = models.TextField()
    approved = models.BooleanField(default=False)
    favourite = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta: 
        ordering = ["-date_added"]
    
    def __str__(self):
        return f"{self.title}"

fontawesome = [
    ('fa-regular fa-thumbs-up', 'thumbs-up'),
    ('fa-regular fa-heart', 'heart'),
    ('fa-regular fa-face-smile', 'face-smile'),
    ('fa-regular fa-face-grin-stars', 'face-grin-stars'),
    ('fa-regular fa-regular fa-face-grin-hearts', 'face-grin-hearts'),
    ('fa-regular fa-face-grin-beam', 'face-grin-beam'),
    ('', 'unselected')
]

class emoji(models.Model):
    fontawesome_classname = models.CharField(max_length=50, choices=fontawesome, default='')
    engagement = models.IntegerField(default = 0)
    account = models.ForeignKey(User, on_delete=models.CASCADE, name="account", default='')
    
    def __str__(self):
        return f"{self.fontawesome_classname}"

top_tips/models.py
from django.db import models
from django.contrib.auth.models import User

class TopTips(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    content = models.TextField()  # Removed max_length
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta: 
        ordering = ["-date_added"]
    
    def __str__(self):
        return self.title  # Simplified __str__ method

project/forms.py
from django import forms
from .models import project_detail, emoji

class project_detailForm(forms.ModelForm):
    class Meta:
        model = project_detail
        fields = ['title', 'summary', 'collaborators', 'deployed_site', 'github_repo', 'reflections', 'approved', 'favourite',]
        widgets = {
            'title' : forms.TextInput (attrs= {
                'class' : 'form-control',
                'placeholder': 'enter project name',
            }),
            'summary': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'enter project summary',
            }),
            'collaborators': forms.Textarea (attrs= {
                'class': 'form-control',
                'placeholder': 'enter name/names'
            }),
            'deployed_site': forms.TextInput (attrs= {
                'class' : 'form-control',
                'placeholder': 'enter deployed link',
            }),
            'github_repo': forms.TextInput (attrs= {
                'class' : 'form-control',
                'placeholder': 'enter repo link',
            }),
            'reflections': forms.Textarea (attrs= {
                'class': 'form-control',
            }),
            'approved': forms.CheckboxInput(attrs={
                'class': 'form-check-input',
            }),
            'favourite': forms.CheckboxInput(attrs={
                'class': 'form-check-input',
            }),
        }

class EmojiSelection(forms.ModelForm):
    class Meta:
        model = emoji
        fields = ['fontawesome_classname',]

project/views.py
from django.shortcuts import render
from django.views import View
from .models import project_detail
from .forms import EmojiSelection, project_detailForm

# Create your views here.

class ProjectView(View):
    def get(self, request):
        approved_projects = project_detail.objects.filter(approved=True)

        return render(
            request, 
            "project/project.html",
            {'projects':approved_projects}
        )

class HomeView(View):
    def get(self, request):

        return render(
            request, 
            "project/index.html",
        )


def dashboard_content(request):

    projects = project_detail.objects.all().order_by("-favourite")

    search = request.GET.get("project-search")
    search_results = project_detail.objects.filter(title__icontains=search).values() if search != None else ''

    if request == 'POST':
        emoji_form = EmojiSelection(data=request.POST)
        if emoji_form.is_valid():
            emoji = emoji_form.save(commit=False)
            emoji.account = request.user
            emoji.save()
    
    emoji_form = EmojiSelection()

    return render(
        request,
        'project/dashboard.html',
        {
            'projects' : projects,
            'search_results' : search_results,
            'emoji_form' : emoji_form,
        },
    )


def project_create_view(request):
    if request.method == 'POST':
        form = project_detailForm(request.POST)
        if form.is_valid():
            return redirect('dashboard') 
    else:
        form = project_detailForm()
    return render (request, 'add.html', {'form':form})

top_tips/views.py
from django.shortcuts import render
from django.views import View
from .models import TopTips


class TopTipsView(View):
    def get(self, request):
        tips = TopTips.objects.all()  # Query the database for all tips
        # Pass the tips to the template
        return render(request, 'top_tips/tips.html', {'tips': tips})

project/templates/project/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
{% if user.is_authenticated %}
<div class="container-fluid">
    <div class="row mt-2 justify-content-center">
        <div class="col-sm-6 col-md-5" id="dashboard-section-one">
            <div class="row ms-1" id="profile-container">
                <div class="col-12" id="profile-image">
                    <img src="{% static 'images/profile-placeholder.jpg' %}" alt="generic profile image">
                </div>
            </div>
            <div class="row text-center">
                <div class="col-12 mt-1" id="profile-username"> {{ user }} </div>
            </div>
            <div class="row mt-3 ms-1" id="toolsbar-container">
                <div class="col-7 p-0" id="search-bar">
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Projects" aria-label="Search" name="project-search">
                        <button class="btn btn-outline-success me-2" type="submit">
                            <i class="fa-solid fa-magnifying-glass"></i>
                        </button>
                    </form>
                </div>
                <div class="col-2 p-0" id="add-btn">
                    <a href="{% url 'project_create' %}"><button class="btn btn-outline-success" type="button">
                        <i class="fa-solid fa-plus"></i>
                    </button></a>
                </div>
                <div class="col-2 p-0" id="expand-toggle">
                    <div class="form-check form-switch">
                        <input class="form-check-input" type="checkbox" id="flexSwitchCheckDefault">
                        <label class="form-check-label" for="flexSwitchCheckDefault"></label>
                    </div>
                </div>
            </div>
            <div class="row mt-3" id="project-list">
                {% if search_results == '' %}
                {% for project in projects %}
                    <div class="col-2">
                        {% if project.favourite == True %}
                        <i class="fa-solid fa-star"></i>
                        {% else %}
                        <i class="fa-regular fa-star"></i>
                        {% endif %}
                    </div>
                    <div class="col-10">
                        <h5> {{ project.title}} </h5>
                        <div class="project-info" style="display: none">
                            <p>{{ project.summary }}</p>
                            <p>Collaborators: {{ project.collaborators }}</p>
                            <div class="row">
                                <div class="col p-0"><img src="{% static 'images/website-image-placeholder.jpg' %}" alt="generic website image"></div>
                                <div class="col p-0">
                                    <a href="{{ project.deployed_site }}" target="_blank" data-bs-toggle="tooltip" data-bs-title="Deployed Site"><i class="fa-solid fa-computer-mouse"></i></a>
                                    <a href="{{ project.github_repo }}" target="_blank" data-bs-toggle="tooltip" data-bs-title="Github Repository"><i class="fa-brands fa-github"></i></a>
                                </div>
                            </div>
                            <p>{{ project.reflections }}</p>
                        </div>
                    </div>
                {% endfor %}
                {% else %}
                {% for result in search_results %}
                <div class="col-2">
                    {% if result.favourite == True %}
                    <i class="fa-solid fa-star"></i>
                    {% else %}
                    <i class="fa-regular fa-star"></i>
                    {% endif %}
                </div>
                <div class="col-10">
                    <h5> {{ result.title}} </h5>
                    <div class="project-info" style="display: none">
                        <p>{{ result.summary }}</p>
                        <p>Collaborators: {{ result.collaborators }}</p>
                        <div class="row">
                            <div class="col p-0"><img src="{% static 'images/website-image-placeholder.jpg' %}" alt="generic website image"></div>
                            <div class="col p-0">
                                <a href="{{ project.deployed_site }}" target="_blank" data-bs-toggle="tooltip" data-bs-title="Deployed Site"><i class="fa-solid fa-computer-mouse"></i></a>
                                <a href="{{ project.github_repo }}" target="_blank" data-bs-toggle="tooltip" data-bs-title="Github Repository"><i class="fa-brands fa-github"></i></a>
                            </div>
                        </div>
                        <p>{{ result.reflections }}</p>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="col-sm-6 col-md-5">
            <div class="row mt-5" id="dashboard-section-two">
                <div class="col text-center">
                    <h2>Emoji Customisation</h2>
                    <p>Choose how viewers engage with your projects</p>
                    <div class="col">
                        {{ emoji_form | crispy }}
                        {% csrf_token %}
                    <div class="col" id="emojis-container">
                        <i class="fa-regular fa-thumbs-up"></i>
                        <i class="fa-regular fa-heart"></i>
                        <i class="fa-regular fa-face-smile"></i>
                        <br>
                        <i class="fa-regular fa-face-grin-stars"></i>
                        <i class="fa-regular fa-face-grin-hearts"></i>
                        <i class="fa-regular fa-face-grin-beam"></i>
                    </div>
                </div>
            </div>
            <div class="row text-center gx-2 mt-3 mb-5" id="dashboard-section-three">
                <h3>Overview</h3>
                <div class="col mt-3">
                    <div class="p-1">
                        <h5>Projects Added</h5>
                        <p> 
                            5
                        </p>
                    </div>
                </div>
                <div class="col mt-3">
                    <div class="p-1">
                        <h5>Awaiting Approval</h5>
                        <p>1</p>
                    </div>
                </div>
                <div class="col mt-3">
                    <div class="p-1">
                        <h5>Total Engagment</h5>
                        <p>12</p>
                    </div>
                </div>
                <!-- <div class="col"> Added</div> -->
            </div>
        </div>
    </div>
</div>
{% endif %}  
{% endblock %} 

project/templates/project/index.html
{% extends "base.html" %}
{% load static %}
{% block title %} Home{% endblock %}

{% block content %}

<div class="container-fluid p-0">
    <img src="{% static 'project/images/developer-coding-imahe.svg' %}" alt="heroimage" class="img-fluid">
</div>
<div class="hero-box p-5 text-center text-black" style="border-radius: 15px; background-color: rgb(178, 224, 239);">
    <div class="hero-box-content">
        <h1 class="display-4">Welcome to Our Community</h1>
        <p class="lead">Celebrating a job well done on your coding project with like-minded community members starts today.</p>
        <p class="lead">Check out our app, a place where you can have your hard work applauded, share tips to help others, and meet new people to collaborate with on upcoming projects.</p>
        <p class="lead mt-4">To get started, click the link below:</p>
        <a href="{% url 'account_signup' %}" class="btn btn-primary mt-3" style="background-color: #5e17eb; color: white;">Sign Up Now</a>
    </div>
</div>

{% endblock %}

project/templates/project/project.html
 {% extends "base.html" %}
{% load static %}

{% block content %}
{% for project in projects %}
<div class="row justify-content-center mt-5">
        <div class="col-10">
            <h5> {{ project.title}} </h5>
            <div class="project-info">
                <div class="row justify-content-center">
                    <div class="col-sm-8"><p>{{ project.summary }}</p></div>
                    <div class="col-sm-4">
                        <img src="{% static 'images/website-image-placeholder.jpg' %}" alt="generic website image">
                        <a href="{{ project.deployed_site }}" target="_blank" data-bs-toggle="tooltip" data-bs-title="Deployed Site"><i class="fa-solid fa-computer-mouse"></i></a>
                        <a href="{{ project.github_repo }}" target="_blank" data-bs-toggle="tooltip" data-bs-title="Github Repository"><i class="fa-brands fa-github"></i></a>
                    </div>
                </div>
                    <p>Developer: {{ project.account }}</p>
                    <p>Collaborators: {{ project.collaborators }}</p>
                    <p>{{ project.reflections }}</p>
                </div>
            </div>
        </div>
</div>
{% endfor %}
{% endblock %}

project_pros/templates/project_pros/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}My Django App{% endblock %}</title>
    
    <!-- Include any CSS files here -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    {% block extra_head %}
    <!-- Any additional head content can be added here -->
    {% endblock %}
</head>
<body>
    <header>
        <div class="logo">
            <img src="{% static 'images/logo.png' %}" alt="Logo">
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'register' %}">Register</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <aside>
            <h2>Top Tips for Junior Developers</h2>
            <ul>
                <li>Understand the basics of version control.</li>
                <li>Write clean, readable code.</li>
                <li>Don’t be afraid to ask questions.</li>
                <li>Learn how to debug your code.</li>
                <li>Practice, practice, practice!</li>
            </ul>
        </aside>

        <section class="content">
            {% block content %}
            <!-- Page-specific content goes here -->
            {% endblock %}
        </section>
    </main>

    <footer>
        <p>&copy; 2024 My Django App. All rights reserved.</p>
        <div class="footer-links">
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'admin:index' %}">Admin Access</a></li>
            </ul>
        </div>
    </footer>

    <!-- Include any JS files here -->
    <script src="{% static 'js/main.js' %}"></script>
    {% block extra_js %}
    <!-- Any additional JavaScript can be added here -->
    {% endblock %}
</body>
</html>

project_pros/templates/project_pros/toptips.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Top Tips for Junior Developers</title>
    
    <!-- Include any CSS files here -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    {% block extra_head %}
    <!-- Any additional head content can be added here -->
    {% endblock %}
</head>
<body>
    <header>
        <div class="logo">
            <img src="{% static 'images/logo.png' %}" alt="Logo">
        </div>
        <nav>
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'register' %}">Register</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section class="content">
            <h1>Top Tips for Junior Developers</h1>
            <p>Whether you're just starting out or looking to improve your skills, these tips are essential for any junior developer:</p>
            <ul>
                <li><strong>Understand the basics of version control:</strong> Learn Git and how to collaborate with others using platforms like GitHub.</li>
                <li><strong>Write clean, readable code:</strong> Follow best practices, such as meaningful naming conventions and proper indentation, to make your code easier to read and maintain.</li>
                <li><strong>Don’t be afraid to ask questions:</strong> Seeking help when you’re stuck is a vital part of learning. Engage with communities and don’t hesitate to ask for guidance.</li>
                <li><strong>Learn how to debug your code:</strong> Knowing how to troubleshoot and resolve issues is crucial. Practice debugging techniques and use tools like debuggers and logging.</li>
                <li><strong>Practice, practice, practice:</strong> The more you code, the better you’ll get. Build small projects, participate in coding challenges, and continuously refine your skills.</li>
            </ul>
        </section>
    </main>

    <footer>
        <p>&copy; 2024 My Django App. All rights reserved.</p>
        <div class="footer-links">
            <ul>
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'admin:index' %}">Admin Access</a></li>
            </ul>
        </div>
    </footer>

    <!-- Include any JS files here -->
    <script src="{% static 'js/main.js' %}"></script>
    {% block extra_js %}
    <!-- Any additional JavaScript can be added here -->
    {% endblock %}
</body>
</html>

templates/add.html
{% extends "base.html" %}
{% block content %}

<div class="container" style="padding: 20px; border-radius: 9px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
    <h2 style="color: #5e17eb; text-align: center; margin-bottom: 20px;">Create New Project</h2>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="id_title" class="form-label" style="color: #5e17eb; font-weight: bold;">Project Title</label>
            {{ form.title }}
        </div>
        <div class="mb-3">
            <label for="id_summary" class="form-label" style="color: #5e17eb; font-weight: bold;">Project Summary</label>
            {{ form.summary }}
        </div>
        <div class="mb-3">
            <label for="id_collaborators" class="form-label" style="color: #5e17eb; font-weight: bold;">Collaborators</label>
            {{ form.collaborators }}
        </div>
        <div class="mb-3">
            <label for="id_deployed_site" class="form-label" style="color: #5e17eb; font-weight: bold;">Deployed Site</label>
            {{ form.deployed_site }}
        </div>
        <div class="mb-3">
            <label for="id_github_repo" class="form-label" style="color: #5e17eb; font-weight: bold;">GitHub Repo</label>
            {{ form.github_repo }}
        </div>
        <div class="mb-3">
            <label for="id_reflections" class="form-label" style="color: #5e17eb; font-weight: bold;">Reflections</label>
            {{ form.reflections }}
        </div>
        <div class="mb-3">
            {{form.approved}} <label for="id_approved" class="form-check-label" style="color: #5e17eb; font-weight: bold;">Approved</label>
        </div>
        <div class="form-check">
            {{ form.favourite }} <label for="id_favourite" class="form-check-label" style="color: #5e17eb; font-weight: bold;">Favourite</label>
        </div>
        <button type="submit" class="btn btn-primary mt-3" style="background-color: #5e17eb; border: none; padding: 10px 20px; font-size: 15px; cursor: pointer; border-radius: 4px; width: 100%;">Submit</button>
    </form>
</div>
{% endblock %}

templates/base.html
{% load static %}

{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'account_logout' as logout_url %}
{% url 'project' as project_url %}
{% url 'dashboard' as dashboard_url %}
{% url 'home' as home_url %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">

    <title>Project Pros</title>

    <!-- Bootstrap5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
    <header>
        <div class="container-fluid g-0 flex-wrap">
            <nav class="navbar navbar-expand-lg navigation">
                <a class="navbar-brand" href="#">
                    <h1 id="logo">&lt<span class="logo-highlight-one">Pro</span>ject <span class="logo-highlight-two">Pro</span>/&gt</h1>
                    <h1 class="hidden logo-sm">&lt <span class="logo-highlight-two">Pro</span> /&gt</h1>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fa-solid fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link {% if request.path == home_url %}is_active{% endif %}" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link {% if request.path == project_url %}is_active{% endif %}" href="{% url 'project' %}">Projects</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == dashboard_url %}is_active{% endif %}" aria-current="page" href="{% url 'dashboard' %}">Dashboard</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == logout_url %}is_active{% endif %}" aria-current="page" href="{% url 'account_logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == signup_url %}is_active{% endif %}" aria-current="page"
                                href="{% url 'account_signup' %}">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == login_url %}is_active{% endif %}" aria-current="page" href="{% url 'account_login' %}">Login</a>
                        </li class="nav-item">
                            <a class="nav-link" href="#">Top Tips!</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </div>
    </header>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div class="alert alert-primary" role="alert">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <main>
        {% block content %}
        <!-- page content -->
        {% endblock %}
    </main>

    <div id="footer-spacer"></div>

    <footer>
        <div class="flex text-center justify-content-center">
            <a href="https://www.facebook.com/" target="_blank"><i class="fa-brands fa-facebook"></i></a>
            <a href="https://www.x.com/" target="_blank"><i class="fa-brands fa-x-twitter"></i></a>
            <a href="https://www.linkedin.com/" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
            <a href="https://www.youtube.com/"target="_blank"><i class="fa-brands fa-youtube"></i></a>
        </div>
        <div class="copyright">
            <p>&copy; 2024 Project Pro</p>
        </div>
    </footer>


    <!-- Bootstrap5 JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/c70f25e1b1.js" crossorigin="anonymous"></script>

    <!-- Custom JS -->
     <script src="{% static 'js/script.js' %}"></script>

</body>

</html>

templates/mfa/authenticate.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <p>
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    </p>
    <form class="authenticate"
          method="POST"
          action="{% url 'mfa_authenticate' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Sign In" %}</button>
    </form>
{% endblock content %}

templates/mfa/index.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    <h1>{% trans "Two-Factor Authentication" %}</h1>
    <section class="totp">
        <h2>{% translate "Authenticator App" %}</h2>
        {% if authenticators.totp %}
            <p>{% translate "Authentication using an authenticator app is active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_deactivate_totp' %}">{% translate "Deactivate" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "An authenticator app is not active." %}</p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_activate_totp' %}">{% translate "Activate" %}</a>
                </li>
            </ul>
        {% endif %}
    </section>
    <section class="recovery_codes">
        <h2>{% translate "Recovery Codes" %}</h2>
        {% if authenticators.recovery_codes %}
            <p>
                {% blocktranslate with total_count=authenticators.recovery_codes.generate_codes|length count unused_count=authenticators.recovery_codes.get_unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
            </p>
            <ul class="actions">
                <li>
                    <a href="{% url 'mfa_view_recovery_codes' %}">{% translate "View codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_download_recovery_codes' %}">{% translate "Download codes" %}</a>
                </li>
                <li>
                    <a href="{% url 'mfa_generate_recovery_codes' %}">{% translate "Generate new codes" %}</a>
                </li>
            </ul>
        {% else %}
            <p>{% translate "No recovery codes set up." %}</p>
        {% endif %}
    </section>
{% endblock content %}

templates/mfa/recovery_codes/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% block content %}
    <h1>{% translate "Recovery Codes" %}</h1>
    <p>
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account. This action will invalidate your existing codes. Are you sure?{% endblocktranslate %}
    </p>
    <form method="POST" action="{% url 'mfa_generate_recovery_codes' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Generate" %}</button>
    </form>
{% endblock content %}

templates/mfa/totp/base.html
{% extends "account/base.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Authenticator App" %}
{% endblock head_title %}